/**
 * Calibration (spec §8.3). Runs C1–C5 and the §8.2 diagnostics for every N and writes
 * reports/calibration.md plus a sample of DATA lines.
 *
 *   npm run calibrate -- --seeds 200
 *   npm run calibrate -- --seeds 200 --params overrides.json --out reports/x.md --json x.json
 *   npm run calibrate -- --data-all          (DATA lines for every C1–C5 run; large, not committed)
 *   npm run calibrate -- --no-diagnostics    (C1–C5 only; faster while tuning)
 */
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { exposureLabel, exposureOf, PARAMS, type Card, type Pace, type Params } from '../src/engine';
import {
  cardDominance,
  collapseDist,
  fixed,
  GREEDY_SHARES,
  greedyCount,
  greedyShareRates,
  halfGreedy,
  allOf,
  LONG_ROUNDS,
  NS,
  passivePath,
  quantile,
  ROUNDS,
  runConditions,
  volatility,
  type NResult,
} from './calibration/scenarios';

function arg(name: string): string | null {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? (process.argv[i + 1] ?? null) : null;
}
const flag = (name: string): boolean => process.argv.includes(`--${name}`);

const seeds = Number(arg('seeds') ?? 200);
const overridesPath = arg('params');
const outPath = arg('out') ?? 'reports/calibration.md';
const dataPath = arg('data') ?? 'reports/calibration-data.txt';
const jsonPath = arg('json');
const skipDiagnostics = flag('no-diagnostics');

const overrides = overridesPath ? (JSON.parse(readFileSync(overridesPath, 'utf8')) as Partial<Params>) : {};
const p: Params = { ...PARAMS, ...overrides };

const fmt = (x: number, dp = 1): string => (x === Infinity ? 'none' : Number.isNaN(x) ? '—' : x.toFixed(dp));
const pct = (x: number): string => `${(x * 100).toFixed(1)}%`;
const PASS = (b: boolean): string => (b ? 'PASS' : 'FAIL');
const pcts = (xs: number[], dp = 1): string => [0.1, 0.25, 0.5, 0.75, 0.9].map((q) => fmt(quantile(xs, q), dp)).join(' / ');

const dataAll = flag('data-all');
mkdirSync(dirname(dataPath), { recursive: true });
writeFileSync(dataPath, '');

const t0 = performance.now();
const results: NResult[] = NS.map((n) => {
  const r = runConditions(p, n, seeds, dataAll);
  if (r.sampleData.length > 0) appendFileSync(dataPath, r.sampleData.join('\n') + '\n');
  r.sampleData = [];
  console.log(`N=${n}: ${r.conditions.map((c) => `${c.id} ${PASS(c.pass)}`).join('  ')}`);
  return r;
});
const allPass = results.every((r) => r.conditions.every((c) => c.pass));

const L: string[] = [];
const line = (s = ''): void => {
  L.push(s);
};
const table = (head: string[], rows: string[][]): void => {
  line(`| ${head.join(' | ')} |`);
  line(`|${head.map(() => '---').join('|')}|`);
  for (const r of rows) line(`| ${r.join(' | ')} |`);
  line();
};

line('# Calibration report');
line();
line(`Generated by \`npm run calibrate -- --seeds ${seeds}\`${overridesPath ? ` with overrides from \`${overridesPath}\`` : ''}.`);
line(`Seeds 1–${seeds} per scenario and N. Default horizon ${ROUNDS} quarters; ${LONG_ROUNDS} where the spec says so.`);
line(`Overall: **${allPass ? 'all C1–C5 conditions pass for every N' : 'one or more conditions fail'}**.`);
line();
line('## Conditions (spec §8.1)');
line();
table(
  ['Condition', ...NS.map((n) => `N=${n}`)],
  (['C1', 'C2', 'C3', 'C4', 'C5'] as const).map((id) => [id, ...results.map((r) => PASS(r.conditions.find((c) => c.id === id)?.pass ?? false))]),
);
line('Definitions used:');
line('- C1: all firms greedy (bot policy: pace 3 or 4, safety 5, BLITZ when allowed). Pass: median moratorium round in 5–9 and ≥ 90% of seeds by round 12. Seeds without a moratorium count as never.');
line('- C2: all firms sustainable (pace 2, safety 15, no card). Pass: moratorium in ≤ 1% of seeds by round 30, and the median per-seed gain of mean firm valuation at round 14 over C1 (same seed) ≥ 40%. Gain = (C2 − C1) / |C1|.');
line('- C3: firm 1 greedy, the rest sustainable. Pass: median per-seed gain of the greedy firm\'s round-14 valuation over the mean sustainable firm\'s ≥ 25%.');
line('- C4: same field as C3. Pass: moratorium by round 14 in ≤ 5% of seeds.');
line('- C5: ⌊N/2⌋ firms greedy, the rest sustainable. Pass: moratorium by round 14 in ≥ 80% of seeds and median moratorium round ≤ 11.');
line();
line('### C1: greedy field');
line();
table(
  ['N', 'median round', 'by round 12', 'by round 14', 'round p10 / p25 / p50 / p75 / p90', 'mean V/firm p10 / p25 / p50 / p75 / p90', 'result'],
  results.map((r) => {
    const c = r.conditions[0]!;
    return [String(r.n), fmt(c.detail.medianRound ?? NaN, 1), pct(c.detail.collapsedBy12 ?? 0), pct(c.detail.collapsedBy14 ?? 0), pcts(r.c1Rounds, 0), pcts(r.c1Values), PASS(c.pass)];
  }),
);
line('### C2: sustainable field');
line();
table(
  ['N', 'moratorium by 30', 'median gain vs C1', 'gain of means', 'mean V/firm at 14: p10 / p25 / p50 / p75 / p90', 'result'],
  results.map((r) => {
    const c = r.conditions[1]!;
    return [String(r.n), pct(c.detail.collapseRateBy30 ?? 0), pct(c.detail.medianValueGainVsC1 ?? 0), pct(c.detail.gainOfMeans ?? 0), pcts(r.c2Values), PASS(c.pass)];
  }),
);
line('### C3: one greedy firm (temptation)');
line();
table(
  ['N', 'median greedy gain', 'gain of means', 'greedy V p10 / p25 / p50 / p75 / p90', 'mean sustainable V p10 / p25 / p50 / p75 / p90', 'result'],
  results.map((r) => {
    const c = r.conditions[2]!;
    return [String(r.n), pct(c.detail.medianGreedyGain ?? 0), pct(c.detail.gainOfMeans ?? 0), pcts(r.c3Greedy), pcts(r.c3Sustainable), PASS(c.pass)];
  }),
);
line('### C4: one greedy firm (no single-firm moratorium)');
line();
table(
  ['N', 'moratorium by 14', 'result'],
  results.map((r) => {
    const c = r.conditions[3]!;
    return [String(r.n), pct(c.detail.collapseRateBy14 ?? 0), PASS(c.pass)];
  }),
);

line('### C5: half the firms greedy (moratorium within a normal session)');
line();
table(
  ['N', 'greedy firms', 'by round 11', 'by round 14', 'median round', 'round p10 / p25 / p50 / p75 / p90', 'result'],
  results.map((r) => {
    const c = r.conditions[4]!;
    return [
      String(r.n),
      String(halfGreedy(r.n).filter((f) => f.kind === 'bot' && f.policy === 'greedy').length),
      pct(c.detail.collapsedBy11 ?? 0),
      pct(c.detail.collapseRateBy14 ?? 0),
      fmt(c.detail.medianRound ?? NaN, 1),
      pcts(r.c5Rounds, 0),
      PASS(c.pass),
    ];
  }),
);

let diagnostics: Record<string, unknown> = {};
if (!skipDiagnostics) {
  line('## Diagnostics (spec §8.2; reported, no hard pass)');
  line();
  line(`### Half greedy, half sustainable (${LONG_ROUNDS} quarters)`);
  line();
  const half = NS.map((n) => ({ n, d: collapseDist(p, seeds, halfGreedy, n) }));
  table(
    ['N', 'by 14', 'by 30', 'round p10 / p25 / p50 / p75 / p90'],
    half.map(({ n, d }) => [String(n), pct(d.rateBy14), pct(d.rateBy30), pcts(d.rounds, 0)]),
  );

  line(`### Greedy share: moratorium by quarter 10 / 12 / 14 (${ROUNDS} quarters)`);
  line();
  line('A room with round(share × N) greedy firms (at least 1); the rest sustainable. The cell gives the greedy firm count, then the share of seeds with a moratorium by quarters 10, 12 and 14.');
  line();
  const shares = GREEDY_SHARES.map(({ label, share }) => ({ label, rows: NS.map((n) => ({ n, k: greedyCount(n, share), r: greedyShareRates(p, seeds, n, share) })) }));
  table(
    ['N', ...shares.map((s) => `${s.label} greedy`)],
    NS.map((n, i) => [
      String(n),
      ...shares.map((s) => {
        const row = s.rows[i]!;
        return `${row.k}: ${pct(row.r.by10)} / ${pct(row.r.by12)} / ${pct(row.r.by14)}`;
      }),
    ]),
  );

  line(`### All Aggressive (pace 3) at safety 0, 15 and 30 (${LONG_ROUNDS} quarters)`);
  line();
  const aggr = [0, 15, 30].map((s) => ({ s, rows: NS.map((n) => ({ n, d: collapseDist(p, seeds, (k) => allOf(k, fixed(3, s)), n) })) }));
  table(
    ['safety', ...NS.map((n) => `N=${n} by 14 / by 30 / median`)],
    aggr.map(({ s, rows }) => [String(s), ...rows.map(({ d }) => `${pct(d.rateBy14)} / ${pct(d.rateBy30)} / ${fmt(quantile(d.rounds, 0.5), 0)}`)]),
  );

  line(`### Passive path: every firm keeps defaults (pace ${p.DEFAULT_PACE}, safety ${p.DEFAULT_SAFETY}) for ${LONG_ROUNDS} quarters`);
  line();
  const passive = NS.map((n) => ({ n, d: passivePath(p, seeds, n) }));
  line(`Stable means: no moratorium in any seed, the p10 trust never falls more than 5 points below the start (${p.T0}), and the median moves less than 2 points over quarters 20–30.`);
  line();
  table(
    ['N', 'moratorium by 30', 'lowest p10 trust', 'median drift q20–q30', 'stable'],
    passive.map(({ n, d }) => {
      const minP10 = Math.min(...d.trust.map((t) => t[0]));
      const drift = (d.trust[LONG_ROUNDS - 1]?.[1] ?? NaN) - (d.trust[19]?.[1] ?? NaN);
      const stable = d.collapseRateBy30 === 0 && minP10 >= p.T0 - 5 && Math.abs(drift) < 2;
      return [String(n), pct(d.collapseRateBy30), fmt(minP10, 2), fmt(drift, 2), stable ? 'yes' : 'no'];
    }),
  );
  line('Trace for N=8: public trust after each quarter: p10, p50 and p90 across seeds, and seed 1.');
  line();
  const p8 = passive.find((x) => x.n === 8)!.d;
  table(
    ['quarter', 'p10', 'p50', 'p90', 'seed 1'],
    p8.trust.map((t, i) => [String(i + 1), fmt(t[0], 2), fmt(t[1], 2), fmt(t[2], 2), fmt(p8.sample[i] ?? NaN, 2)]),
  );

  line(`### Card dominance: myopic best response against a greedy field (${ROUNDS} quarters)`);
  line();
  line('Firm 1 plays pace 4 and 3 alternately at safety 5 and, each quarter, the legal card that maximises its own valuation at the end of that quarter. Pass: no card chosen in more than 60% of rounds.');
  line();
  const cards = NS.map((n) => ({ n, c: cardDominance(p, seeds, n) }));
  const CARD_LIST: Card[] = ['NONE', 'POACH', 'PUBLISH', 'LOBBY', 'BLITZ'];
  table(
    ['N', ...CARD_LIST, 'max card share', 'result'],
    cards.map(({ n, c }) => {
      const total = CARD_LIST.reduce((a, k) => a + c[k], 0);
      const maxCard = Math.max(...CARD_LIST.filter((k) => k !== 'NONE').map((k) => c[k])) / total;
      return [String(n), ...CARD_LIST.map((k) => pct(c[k] / total)), pct(maxCard), maxCard <= 0.6 ? 'PASS' : 'FAIL'];
    }),
  );

  line(`### Leaderboard volatility: mixed field (cautious, standard, greedy, mimic-leader), disclosure on`);
  line();
  const vol = NS.map((n) => ({ n, v: volatility(p, seeds, n) }));
  table(
    ['N', 'firms changing rank per quarter', 'mean absolute rank change per firm'],
    vol.map(({ n, v }) => [String(n), fmt(v.meanChanged, 2), fmt(v.meanAbsDelta, 2)]),
  );

  line('### Public exposure labels by decision');
  line();
  table(
    ['pace', 'safety 0', 'safety 10', 'safety 15', 'safety 30'],
    ([1, 2, 3, 4] as Pace[]).map((pace) => [
      String(pace),
      ...[0, 10, 15, 30].map((s) => `${fmt(exposureOf(pace, s, p), 2)} ${exposureLabel(exposureOf(pace, s, p), p)}`),
    ]),
  );
  diagnostics = { half, shares, passive: passive.map(({ n, d }) => ({ n, rate: d.collapseRateBy30 })), cards, vol };
}

line('## Parameters used');
line();
table(
  ['name', 'value'],
  Object.entries(p).map(([k, v]) => [k, JSON.stringify(v)]),
);

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, L.join('\n'));

if (jsonPath) {
  writeFileSync(jsonPath, JSON.stringify({ allPass, conditions: results.map((r) => r.conditions), diagnostics }, null, 1));
}

console.log(`${allPass ? 'All C1–C5 pass' : 'Some conditions fail'}. Wrote ${outPath} and ${dataPath} in ${((performance.now() - t0) / 1000).toFixed(1)} s.`);
